spring.application.name=currencyconverter

server.port=8081

# H2 in-memory DB (swap for real DB in production)
spring.h2.console.path=/h2
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:mem:transactionsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#(create, update, create-drop, validate)
spring.jpa.hibernate.ddl-auto=update

# SSL Certificate Store
spring.ssl.bundle.jks.my-bundle.keystore.location=classpath:./static/currencyconverter.p12
spring.ssl.bundle.jks.my-bundle.keystore.password=changeIt
spring.ssl.bundle.jks.my-bundle.keystore.type=PKCS12
spring.ssl.bundle.jks.mybundle.key.alias=tomcat
server.ssl.bundle=my-bundle
server.ssl.enabled=false

#Enable caching for Caffine
spring.cache.type=caffeine
spring.cache.cache-names=exchangerateresponsedto
spring.cache.caffeine.spec=initialCapacity=100,maximumSize=500,expireAfterWrite=10m

#UTF-8 Support for L10N
spring.messages.encoding=UTF-8

# Customizing the JSON API definition path
springdoc.api-docs.path=/api-docs

# Customizing the HTML UI layout path
springdoc.swagger-ui.path=/swagger-ui.html